HEADERS = slalib.h  slamac.h
OBJECTS = addet.o airmas.o amp.o ampqk.o aop.o aoppa.o aoppat.o aopqk.o aopqkx.o caldj.o calyd.o cldj.o dat.o dbear.o dc62s.o dcc2s.o dcmpf.o dcs2c.o dd2tf.o deuler.o dimxv.o djcal.o djcl.o dm2av.o dmat.o dmoon.o dmxm.o dmxv.o dr2af.o dr2tf.o drange.o dranrm.o ds2c6.o ds2tp.o dsep.o dtf2d.o dtf2r.o dt.o dtp2s.o dtt.o dvdv.o dvn.o dvxv.o ecleq.o ecmat.o eg50.o el2ue.o epb2d.o epb.o epj2d.o epj.o eqecl.o eqeqx.o eqgal.o etrms.o evp.o fitxy.o fk425.o fk45z.o fk524.o fk54z.o galeq.o galsup.o ge50.o geoc.o gmst.o gresid.o imxv.o invf.o m2av.o map.o mappa.o mapqk.o mapqkx.o mapqkz.o moon.o mxm.o mxv.o nutc.o nut.o oap.o oapqk.o obs.o pa.o pcd.o planel.o planet.o pm.o prebn.o preces.o prec.o prenut.o pv2ue.o pvobs.o pxy.o random.o rcc.o rdplan.o refco.o refro.o refv.o refz.o subet.o supgal.o svdcov.o svd.o svdsol.o ue2pv.o unpcd.o vn.o vxv.o xy2xy.o zd.o
TARGET  = libsla.a
MAKE_TARGET = $(MAKE_LIB_TARGET)
include ../../include/Makefile.inc
