HEADERS = guide.h
OBJECTS = azelrot.o  defocus.o  detector.o  elerotcorr.o  quickcenter.o  transfer.o  xyfit.o  xytoazel.o guidserv.o
LIBS    = -lfuntools -lmsg -lparam -lutil -lsla -lm
TARGET  = guidserv
MAKE_TARGET = $(MAKE_SERVER_TARGET)
include ../../include/Makefile.inc
