HEADERS = cache.h except.h filelist.h range.h sokmult.h xfile.h xlist.h xos.h
OBJECTS = bsearch.o cache.o caldate.o coproc.o except.o f77handle.o f77.o filelist.o getdate.o muxio.o poll.o range.o readfile.o saotng.o shm.o sleep.o slurpline.o sokfile.o sokmult.o strtod.o strupr.o termcap.o tmatch.o xfile.o xlist.o xpipe.o
TARGET  = libutil.a
MAKE_TARGET = $(MAKE_LIB_TARGET)
include ../../include/Makefile.inc
