/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /data/mmti/CVSROOT/param/iarg_lex.c,v 1.3 2004/04/07 19:09:41 john Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define iargconst const
#else
#define iargconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN iarg_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((iarg_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE iargrestart( iargin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct iarg_buffer_state *YY_BUFFER_STATE;

extern int iargleng;
extern FILE *iargin, *iargout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		iargless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the iargless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define iargless(n) \
	do \
		{ \
		/* Undo effects of setting up iargtext. */ \
		*iarg_cp = iarg_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		iarg_c_buf_p = iarg_cp = iarg_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up iargtext again */ \
		} \
	while ( 0 )

#define unput(c) iargunput( c, iargtext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int iarg_size_t;


struct iarg_buffer_state
	{
	FILE *iarg_input_file;

	char *iarg_ch_buf;		/* input buffer */
	char *iarg_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	iarg_size_t iarg_buf_size;

	/* Number of characters read into iarg_ch_buf, not including EOB
	 * characters.
	 */
	int iarg_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int iarg_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int iarg_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int iarg_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int iarg_fill_buffer;

	int iarg_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via iargrestart()), so that the user can continue scanning by
	 * just pointing iargin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE iarg_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER iarg_current_buffer


/* iarg_hold_char holds the character lost when iargtext is formed. */
static char iarg_hold_char;

static int iarg_n_chars;		/* number of characters read into iarg_ch_buf */


int iargleng;

/* Points to current character in buffer. */
static char *iarg_c_buf_p = (char *) 0;
static int iarg_init = 1;		/* whether we need to initialize */
static int iarg_start = 0;	/* start state number */

/* Flag which is used to allow iargwrap()'s to do buffer switches
 * instead of setting up a fresh iargin.  A bit of a hack ...
 */
static int iarg_did_buffer_switch_on_eof;

void iargrestart YY_PROTO(( FILE *input_file ));

void iarg_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void iarg_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE iarg_create_buffer YY_PROTO(( FILE *file, int size ));
void iarg_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void iarg_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void iarg_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER iarg_flush_buffer( iarg_current_buffer )

YY_BUFFER_STATE iarg_scan_buffer YY_PROTO(( char *base, iarg_size_t size ));
YY_BUFFER_STATE iarg_scan_string YY_PROTO(( iargconst char *iarg_str ));
YY_BUFFER_STATE iarg_scan_bytes YY_PROTO(( iargconst char *bytes, int len ));

static void *iarg_flex_alloc YY_PROTO(( iarg_size_t ));
static void *iarg_flex_realloc YY_PROTO(( void *, iarg_size_t ));
static void iarg_flex_free YY_PROTO(( void * ));

#define iarg_new_buffer iarg_create_buffer

#define iarg_set_interactive(is_interactive) \
	{ \
	if ( ! iarg_current_buffer ) \
		iarg_current_buffer = iarg_create_buffer( iargin, YY_BUF_SIZE ); \
	iarg_current_buffer->iarg_is_interactive = is_interactive; \
	}

#define iarg_set_bol(at_bol) \
	{ \
	if ( ! iarg_current_buffer ) \
		iarg_current_buffer = iarg_create_buffer( iargin, YY_BUF_SIZE ); \
	iarg_current_buffer->iarg_at_bol = at_bol; \
	}

#define YY_AT_BOL() (iarg_current_buffer->iarg_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *iargin = (FILE *) 0, *iargout = (FILE *) 0;
typedef int iarg_state_type;
extern char *iargtext;
#define iargtext_ptr iargtext

static iarg_state_type iarg_get_previous_state YY_PROTO(( void ));
static iarg_state_type iarg_try_NUL_trans YY_PROTO(( iarg_state_type current_state ));
static int iarg_get_next_buffer YY_PROTO(( void ));
static void iarg_fatal_error YY_PROTO(( iargconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up iargtext.
 */
#define YY_DO_BEFORE_ACTION \
	iargtext_ptr = iarg_bp; \
	iargleng = (int) (iarg_cp - iarg_bp); \
	iarg_hold_char = *iarg_cp; \
	*iarg_cp = '\0'; \
	iarg_c_buf_p = iarg_cp;

#define YY_NUM_RULES 9
#define YY_END_OF_BUFFER 10
static iargconst short int iarg_acclist[74] =
    {   0,
        8,    8,    8,    8,    8,    8,   10,    8,    9,    6,
        9,    6,    9,16386,    3,    9,    4,    6,    9,    5,
        6,    9,    6,    7,    9,    6,    7,    9,16386,    3,
        7,    9,    8,    6,    6,    6,16386,    6,    6,16386,
        6,16386, 8194,    6,    7,    7,    6,    7,    6,    7,
    16386,    6,    7,    6,    7,16386,    6,    7,16386, 8194,
        7,    6,    1,    1,    6,    7,    7,    6,    6,    6,
        7,    6,    7
    } ;

static iargconst short int iarg_accept[46] =
    {   0,
        1,    2,    3,    4,    5,    6,    7,    8,   10,   12,
       15,   17,   20,   23,   26,   30,   33,   34,   35,   36,
       36,   38,   39,   41,   43,   44,   46,   47,   49,   52,
       54,   57,   60,   62,   63,   63,   64,   65,   67,   68,
       69,   70,   72,   74,   74
    } ;

static iargconst int iarg_ec[256] =
    {   0,
        1,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    3,    2,    2,    2,    2,
        2,    2,    4,    2,    5,    6,    2,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    2,    2,    2,
        7,    2,    2,    2,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        8,    2,    9,    2,    6,    2,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2
    } ;

static iargconst int iarg_meta[10] =
    {   0,
        1,    2,    2,    2,    2,    2,    3,    2,    2
    } ;

static iargconst short int iarg_base[54] =
    {   0,
        0,    7,   11,    0,   16,   23,   55,   53,   45,   30,
       98,   44,   21,   33,   41,    0,   27,   19,   18,   50,
        0,   57,   65,   19,   98,   62,    0,   14,    0,   19,
       70,   15,    0,   67,    4,   98,    0,   70,    3,    0,
        2,    0,    0,   98,   79,   82,    0,   84,   86,   88,
       90,   92,   94
    } ;

static iargconst short int iarg_def[54] =
    {   0,
       45,   45,    2,    3,   46,   46,   44,   44,   47,   44,
       44,   47,   47,   48,   44,   49,   44,   47,   50,   44,
       10,   47,   10,   10,   44,   48,   49,   51,   15,   26,
       15,   15,   49,   50,   52,   44,   20,   51,   53,   34,
       52,   38,   53,    0,   44,   44,   44,   44,   44,   44,
       44,   44,   44
    } ;

static iargconst short int iarg_nxt[108] =
    {   0,
        8,   18,   10,   44,   44,   44,   11,    8,   43,   10,
       41,   43,   41,   11,   12,   13,    8,   32,   15,   36,
       39,   24,   16,    8,   35,   15,   19,   17,   19,   16,
       20,   18,   21,   22,   23,   24,   25,   19,   18,   27,
       28,   20,   26,   29,   30,   31,   32,   33,   28,   26,
       20,   19,   19,   17,   44,   44,   25,   36,   44,   44,
       44,   44,   44,   44,   19,   37,   44,   24,   27,   28,
       37,   44,   32,   35,   44,   40,   39,   44,   42,    9,
        9,    9,   14,   14,   14,   26,   26,   27,   27,   34,
       34,   38,   38,   35,   35,   39,   39,    7,   44,   44,

       44,   44,   44,   44,   44,   44,   44
    } ;

static iargconst short int iarg_chk[108] =
    {   0,
        1,   47,    1,    0,    0,    0,    1,    2,   43,    2,
       41,   39,   35,    2,    3,    3,    5,   32,    5,   30,
       28,   24,    5,    6,   19,    6,   18,   17,   13,    6,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   14,
       14,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       20,   12,    9,    8,    7,    0,   20,   22,    0,    0,
        0,    0,    0,    0,   22,   23,    0,   23,   26,   26,
       31,    0,   31,   34,    0,   34,   38,    0,   38,   45,
       45,   45,   46,   46,   46,   48,   48,   49,   49,   50,
       50,   51,   51,   52,   52,   53,   53,   44,   44,   44,

       44,   44,   44,   44,   44,   44,   44
    } ;

static iarg_state_type iarg_state_buf[YY_BUF_SIZE + 2], *iarg_state_ptr;
static char *iarg_full_match;
static int iarg_lp;
static int iarg_looking_for_trail_begin = 0;
static int iarg_full_lp;
static int *iarg_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*iarg_cp = iarg_hold_char; /* undo effects of setting up iargtext */ \
iarg_cp = iarg_full_match; /* restore poss. backed-over text */ \
iarg_lp = iarg_full_lp; /* restore orig. accepting pos. */ \
iarg_state_ptr = iarg_full_state; /* restore orig. state */ \
iarg_current_state = *iarg_state_ptr; /* restore curr. state */ \
++iarg_lp; \
goto find_rule; \
}
#define iargmore() iargmore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *iargtext;
#line 1 "iarg.l"
#define INITIAL 0
#define NAMED 1

#define VALED 2

#line 11 "iarg.l"

#include <string.h>
#include <stdlib.h>

#include "pfile.h"
#include "pargs.h"
#include "iarg.h"

#define YY_SKIP_YYWRAP

extern int t_valu;

#define StrCpy(res, str, len)	( strncpy((res=malloc(len + 1)), str, len),\
					res[len] = '\0', res)

#undef  YY_INPUT
#define YY_INPUT(buf,result,max_size)	{				\
		if ( *buf = ArgvChar(((ArgStream) iargin)) )		\
			result = 1;					\
		else							\
			result = YY_NULL;				\
	}

/* default iargwrap function - always treat EOF as an EOF */
iargwrap() {
	return 1;
}
#line 456 "lex.iarg.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int iargwrap YY_PROTO(( void ));
#else
extern int iargwrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void iargunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef iargtext_ptr
static void iarg_flex_strncpy YY_PROTO(( char *, iargconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int iarg_flex_strlen YY_PROTO(( iargconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int iarginput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int iarg_start_stack_ptr = 0;
static int iarg_start_stack_depth = 0;
static int *iarg_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void iarg_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void iarg_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int iarg_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( iargtext, iargleng, 1, iargout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( iarg_current_buffer->iarg_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( iargin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( iargin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, iargin )) == 0) \
		  && ferror( iargin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "iargterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef iargterminate
#define iargterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) iarg_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int iarglex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after iargtext and iargleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register iarg_state_type iarg_current_state;
	register char *iarg_cp, *iarg_bp;
	register int iarg_act;

#line 40 "iarg.l"


#line 610 "lex.iarg.c"

	if ( iarg_init )
		{
		iarg_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! iarg_start )
			iarg_start = 1;	/* first start state */

		if ( ! iargin )
			iargin = stdin;

		if ( ! iargout )
			iargout = stdout;

		if ( ! iarg_current_buffer )
			iarg_current_buffer =
				iarg_create_buffer( iargin, YY_BUF_SIZE );

		iarg_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		iarg_cp = iarg_c_buf_p;

		/* Support of iargtext. */
		*iarg_cp = iarg_hold_char;

		/* iarg_bp points to the position in iarg_ch_buf of the start of
		 * the current run.
		 */
		iarg_bp = iarg_cp;

		iarg_current_state = iarg_start;
		iarg_state_ptr = iarg_state_buf;
		*iarg_state_ptr++ = iarg_current_state;
iarg_match:
		do
			{
			register YY_CHAR iarg_c = iarg_ec[YY_SC_TO_UI(*iarg_cp)];
			while ( iarg_chk[iarg_base[iarg_current_state] + iarg_c] != iarg_current_state )
				{
				iarg_current_state = (int) iarg_def[iarg_current_state];
				if ( iarg_current_state >= 45 )
					iarg_c = iarg_meta[(unsigned int) iarg_c];
				}
			iarg_current_state = iarg_nxt[iarg_base[iarg_current_state] + (unsigned int) iarg_c];
			*iarg_state_ptr++ = iarg_current_state;
			++iarg_cp;
			}
		while ( iarg_base[iarg_current_state] != 98 );

iarg_find_action:
		iarg_current_state = *--iarg_state_ptr;
		iarg_lp = iarg_accept[iarg_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( iarg_lp && iarg_lp < iarg_accept[iarg_current_state + 1] )
				{
				iarg_act = iarg_acclist[iarg_lp];
				if ( iarg_act & YY_TRAILING_HEAD_MASK ||
				     iarg_looking_for_trail_begin )
					{
					if ( iarg_act == iarg_looking_for_trail_begin )
						{
						iarg_looking_for_trail_begin = 0;
						iarg_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( iarg_act & YY_TRAILING_MASK )
					{
					iarg_looking_for_trail_begin = iarg_act & ~YY_TRAILING_MASK;
					iarg_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					iarg_full_match = iarg_cp;
					iarg_full_state = iarg_state_ptr;
					iarg_full_lp = iarg_lp;
					break;
					}
				++iarg_lp;
				goto find_rule;
				}
			--iarg_cp;
			iarg_current_state = *--iarg_state_ptr;
			iarg_lp = iarg_accept[iarg_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( iarg_act )
	{ /* beginning of action switch */
case 1:
*iarg_cp = iarg_hold_char; /* undo effects of setting up iargtext */
iarg_c_buf_p = iarg_cp -= 2;
YY_DO_BEFORE_ACTION; /* set up iargtext again */
YY_RULE_SETUP
#line 42 "iarg.l"
{ /* Match a shortcut boolean assignment
		  ** The [+-] must be contigious to the name.
		  **/
			StrCpy(iarglval.stri, iargtext, iargleng);
			BEGIN(NAMED);
			return T_name;
		}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 49 "iarg.l"
{ /* Normal <name> = <value>
		  **/
			StrCpy(iarglval.stri, iargtext, iargleng);
			BEGIN(NAMED);
			return T_name;
		}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 55 "iarg.l"
{ /* Snag the assignment.
		  ** Note that positional parameters are done.
		  **/
			t_valu = T_valu;
			BEGIN(VALED);
			return '=';
		}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 62 "iarg.l"
{
			StrCpy(iarglval.stri, "yes", 3);
			BEGIN(0);
			return T_mark;	}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 66 "iarg.l"
{
			StrCpy(iarglval.stri, "no",  2);
			BEGIN(0);
			return T_mark;	}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 70 "iarg.l"
{ /* A normal value (= not allowed, except in [])
		  **/
                        if ( iargleng == 2 && !strncmp(iargtext, "\"\"", 2) )
                          StrCpy(iarglval.stri, "", 0);
                        else
                          StrCpy(iarglval.stri, iargtext, iargleng);

			BEGIN(0);
			return t_valu;
		}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 81 "iarg.l"
{
			StrCpy(iarglval.stri, iargtext, iargleng);
			BEGIN(0);
			return T_valu;
		}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 87 "iarg.l"
{
			BEGIN(0);
		}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 90 "iarg.l"
ECHO;
	YY_BREAK
#line 800 "lex.iarg.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(NAMED):
			case YY_STATE_EOF(VALED):
				iargterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int iarg_amount_of_matched_text = (int) (iarg_cp - iargtext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*iarg_cp = iarg_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( iarg_current_buffer->iarg_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed iargin at a new source and called
			 * iarglex().  If so, then we have to assure
			 * consistency between iarg_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			iarg_n_chars = iarg_current_buffer->iarg_n_chars;
			iarg_current_buffer->iarg_input_file = iargin;
			iarg_current_buffer->iarg_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for iarg_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since iarg_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( iarg_c_buf_p <= &iarg_current_buffer->iarg_ch_buf[iarg_n_chars] )
			{ /* This was really a NUL. */
			iarg_state_type iarg_next_state;

			iarg_c_buf_p = iargtext_ptr + iarg_amount_of_matched_text;

			iarg_current_state = iarg_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * iarg_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			iarg_next_state = iarg_try_NUL_trans( iarg_current_state );

			iarg_bp = iargtext_ptr + YY_MORE_ADJ;

			if ( iarg_next_state )
				{
				/* Consume the NUL. */
				iarg_cp = ++iarg_c_buf_p;
				iarg_current_state = iarg_next_state;
				goto iarg_match;
				}

			else
				{
				iarg_cp = iarg_c_buf_p;
				goto iarg_find_action;
				}
			}

		else switch ( iarg_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				iarg_did_buffer_switch_on_eof = 0;

				if ( iargwrap() )
					{
					/* Note: because we've taken care in
					 * iarg_get_next_buffer() to have set up
					 * iargtext, we can now set up
					 * iarg_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					iarg_c_buf_p = iargtext_ptr + YY_MORE_ADJ;

					iarg_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! iarg_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				iarg_c_buf_p =
					iargtext_ptr + iarg_amount_of_matched_text;

				iarg_current_state = iarg_get_previous_state();

				iarg_cp = iarg_c_buf_p;
				iarg_bp = iargtext_ptr + YY_MORE_ADJ;
				goto iarg_match;

			case EOB_ACT_LAST_MATCH:
				iarg_c_buf_p =
				&iarg_current_buffer->iarg_ch_buf[iarg_n_chars];

				iarg_current_state = iarg_get_previous_state();

				iarg_cp = iarg_c_buf_p;
				iarg_bp = iargtext_ptr + YY_MORE_ADJ;
				goto iarg_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of iarglex */


/* iarg_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int iarg_get_next_buffer()
	{
	register char *dest = iarg_current_buffer->iarg_ch_buf;
	register char *source = iargtext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( iarg_c_buf_p > &iarg_current_buffer->iarg_ch_buf[iarg_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( iarg_current_buffer->iarg_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( iarg_c_buf_p - iargtext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (iarg_c_buf_p - iargtext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( iarg_current_buffer->iarg_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		iarg_current_buffer->iarg_n_chars = iarg_n_chars = 0;

	else
		{
		int num_to_read =
			iarg_current_buffer->iarg_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = iarg_current_buffer;

			int iarg_c_buf_p_offset =
				(int) (iarg_c_buf_p - b->iarg_ch_buf);

			if ( b->iarg_is_our_buffer )
				{
				int new_size = b->iarg_buf_size * 2;

				if ( new_size <= 0 )
					b->iarg_buf_size += b->iarg_buf_size / 8;
				else
					b->iarg_buf_size *= 2;

				b->iarg_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					iarg_flex_realloc( (void *) b->iarg_ch_buf,
							 b->iarg_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->iarg_ch_buf = 0;

			if ( ! b->iarg_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			iarg_c_buf_p = &b->iarg_ch_buf[iarg_c_buf_p_offset];

			num_to_read = iarg_current_buffer->iarg_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&iarg_current_buffer->iarg_ch_buf[number_to_move]),
			iarg_n_chars, num_to_read );

		iarg_current_buffer->iarg_n_chars = iarg_n_chars;
		}

	if ( iarg_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			iargrestart( iargin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			iarg_current_buffer->iarg_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	iarg_n_chars += number_to_move;
	iarg_current_buffer->iarg_ch_buf[iarg_n_chars] = YY_END_OF_BUFFER_CHAR;
	iarg_current_buffer->iarg_ch_buf[iarg_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	iargtext_ptr = &iarg_current_buffer->iarg_ch_buf[0];

	return ret_val;
	}


/* iarg_get_previous_state - get the state just before the EOB char was reached */

static iarg_state_type iarg_get_previous_state()
	{
	register iarg_state_type iarg_current_state;
	register char *iarg_cp;

	iarg_current_state = iarg_start;
	iarg_state_ptr = iarg_state_buf;
	*iarg_state_ptr++ = iarg_current_state;

	for ( iarg_cp = iargtext_ptr + YY_MORE_ADJ; iarg_cp < iarg_c_buf_p; ++iarg_cp )
		{
		register YY_CHAR iarg_c = (*iarg_cp ? iarg_ec[YY_SC_TO_UI(*iarg_cp)] : 2);
		while ( iarg_chk[iarg_base[iarg_current_state] + iarg_c] != iarg_current_state )
			{
			iarg_current_state = (int) iarg_def[iarg_current_state];
			if ( iarg_current_state >= 45 )
				iarg_c = iarg_meta[(unsigned int) iarg_c];
			}
		iarg_current_state = iarg_nxt[iarg_base[iarg_current_state] + (unsigned int) iarg_c];
		*iarg_state_ptr++ = iarg_current_state;
		}

	return iarg_current_state;
	}


/* iarg_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = iarg_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static iarg_state_type iarg_try_NUL_trans( iarg_state_type iarg_current_state )
#else
static iarg_state_type iarg_try_NUL_trans( iarg_current_state )
iarg_state_type iarg_current_state;
#endif
	{
	register int iarg_is_jam;

	register YY_CHAR iarg_c = 2;
	while ( iarg_chk[iarg_base[iarg_current_state] + iarg_c] != iarg_current_state )
		{
		iarg_current_state = (int) iarg_def[iarg_current_state];
		if ( iarg_current_state >= 45 )
			iarg_c = iarg_meta[(unsigned int) iarg_c];
		}
	iarg_current_state = iarg_nxt[iarg_base[iarg_current_state] + (unsigned int) iarg_c];
	iarg_is_jam = (iarg_current_state == 44);
	if ( ! iarg_is_jam )
		*iarg_state_ptr++ = iarg_current_state;

	return iarg_is_jam ? 0 : iarg_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void iargunput( int c, register char *iarg_bp )
#else
static void iargunput( c, iarg_bp )
int c;
register char *iarg_bp;
#endif
	{
	register char *iarg_cp = iarg_c_buf_p;

	/* undo effects of setting up iargtext */
	*iarg_cp = iarg_hold_char;

	if ( iarg_cp < iarg_current_buffer->iarg_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = iarg_n_chars + 2;
		register char *dest = &iarg_current_buffer->iarg_ch_buf[
					iarg_current_buffer->iarg_buf_size + 2];
		register char *source =
				&iarg_current_buffer->iarg_ch_buf[number_to_move];

		while ( source > iarg_current_buffer->iarg_ch_buf )
			*--dest = *--source;

		iarg_cp += (int) (dest - source);
		iarg_bp += (int) (dest - source);
		iarg_current_buffer->iarg_n_chars =
			iarg_n_chars = iarg_current_buffer->iarg_buf_size;

		if ( iarg_cp < iarg_current_buffer->iarg_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--iarg_cp = (char) c;


	iargtext_ptr = iarg_bp;
	iarg_hold_char = *iarg_cp;
	iarg_c_buf_p = iarg_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int iarginput()
#else
static int input()
#endif
	{
	int c;

	*iarg_c_buf_p = iarg_hold_char;

	if ( *iarg_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* iarg_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( iarg_c_buf_p < &iarg_current_buffer->iarg_ch_buf[iarg_n_chars] )
			/* This was really a NUL. */
			*iarg_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = iarg_c_buf_p - iargtext_ptr;
			++iarg_c_buf_p;

			switch ( iarg_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because iarg_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					iargrestart( iargin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( iargwrap() )
						return EOF;

					if ( ! iarg_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return iarginput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					iarg_c_buf_p = iargtext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) iarg_c_buf_p;	/* cast for 8-bit char's */
	*iarg_c_buf_p = '\0';	/* preserve iargtext */
	iarg_hold_char = *++iarg_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void iargrestart( FILE *input_file )
#else
void iargrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! iarg_current_buffer )
		iarg_current_buffer = iarg_create_buffer( iargin, YY_BUF_SIZE );

	iarg_init_buffer( iarg_current_buffer, input_file );
	iarg_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void iarg_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void iarg_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( iarg_current_buffer == new_buffer )
		return;

	if ( iarg_current_buffer )
		{
		/* Flush out information for old buffer. */
		*iarg_c_buf_p = iarg_hold_char;
		iarg_current_buffer->iarg_buf_pos = iarg_c_buf_p;
		iarg_current_buffer->iarg_n_chars = iarg_n_chars;
		}

	iarg_current_buffer = new_buffer;
	iarg_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (iargwrap()) processing, but the only time this flag
	 * is looked at is after iargwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	iarg_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void iarg_load_buffer_state( void )
#else
void iarg_load_buffer_state()
#endif
	{
	iarg_n_chars = iarg_current_buffer->iarg_n_chars;
	iargtext_ptr = iarg_c_buf_p = iarg_current_buffer->iarg_buf_pos;
	iargin = iarg_current_buffer->iarg_input_file;
	iarg_hold_char = *iarg_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE iarg_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE iarg_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) iarg_flex_alloc( sizeof( struct iarg_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in iarg_create_buffer()" );

	b->iarg_buf_size = size;

	/* iarg_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->iarg_ch_buf = (char *) iarg_flex_alloc( b->iarg_buf_size + 2 );
	if ( ! b->iarg_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in iarg_create_buffer()" );

	b->iarg_is_our_buffer = 1;

	iarg_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void iarg_delete_buffer( YY_BUFFER_STATE b )
#else
void iarg_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == iarg_current_buffer )
		iarg_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->iarg_is_our_buffer )
		iarg_flex_free( (void *) b->iarg_ch_buf );

	iarg_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void iarg_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void iarg_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	iarg_flush_buffer( b );

	b->iarg_input_file = file;
	b->iarg_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->iarg_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->iarg_is_interactive = 0;
#else
	b->iarg_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void iarg_flush_buffer( YY_BUFFER_STATE b )
#else
void iarg_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->iarg_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->iarg_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->iarg_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->iarg_buf_pos = &b->iarg_ch_buf[0];

	b->iarg_at_bol = 1;
	b->iarg_buffer_status = YY_BUFFER_NEW;

	if ( b == iarg_current_buffer )
		iarg_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE iarg_scan_buffer( char *base, iarg_size_t size )
#else
YY_BUFFER_STATE iarg_scan_buffer( base, size )
char *base;
iarg_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) iarg_flex_alloc( sizeof( struct iarg_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in iarg_scan_buffer()" );

	b->iarg_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->iarg_buf_pos = b->iarg_ch_buf = base;
	b->iarg_is_our_buffer = 0;
	b->iarg_input_file = 0;
	b->iarg_n_chars = b->iarg_buf_size;
	b->iarg_is_interactive = 0;
	b->iarg_at_bol = 1;
	b->iarg_fill_buffer = 0;
	b->iarg_buffer_status = YY_BUFFER_NEW;

	iarg_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE iarg_scan_string( iargconst char *iarg_str )
#else
YY_BUFFER_STATE iarg_scan_string( iarg_str )
iargconst char *iarg_str;
#endif
	{
	int len;
	for ( len = 0; iarg_str[len]; ++len )
		;

	return iarg_scan_bytes( iarg_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE iarg_scan_bytes( iargconst char *bytes, int len )
#else
YY_BUFFER_STATE iarg_scan_bytes( bytes, len )
iargconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	iarg_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) iarg_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in iarg_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = iarg_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in iarg_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->iarg_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void iarg_push_state( int new_state )
#else
static void iarg_push_state( new_state )
int new_state;
#endif
	{
	if ( iarg_start_stack_ptr >= iarg_start_stack_depth )
		{
		iarg_size_t new_size;

		iarg_start_stack_depth += YY_START_STACK_INCR;
		new_size = iarg_start_stack_depth * sizeof( int );

		if ( ! iarg_start_stack )
			iarg_start_stack = (int *) iarg_flex_alloc( new_size );

		else
			iarg_start_stack = (int *) iarg_flex_realloc(
					(void *) iarg_start_stack, new_size );

		if ( ! iarg_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	iarg_start_stack[iarg_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void iarg_pop_state()
	{
	if ( --iarg_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(iarg_start_stack[iarg_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int iarg_top_state()
	{
	return iarg_start_stack[iarg_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void iarg_fatal_error( iargconst char msg[] )
#else
static void iarg_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine iargless() so it works in section 3 code. */

#undef iargless
#define iargless(n) \
	do \
		{ \
		/* Undo effects of setting up iargtext. */ \
		iargtext[iargleng] = iarg_hold_char; \
		iarg_c_buf_p = iargtext + n; \
		iarg_hold_char = *iarg_c_buf_p; \
		*iarg_c_buf_p = '\0'; \
		iargleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef iargtext_ptr
#ifdef YY_USE_PROTOS
static void iarg_flex_strncpy( char *s1, iargconst char *s2, int n )
#else
static void iarg_flex_strncpy( s1, s2, n )
char *s1;
iargconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int iarg_flex_strlen( iargconst char *s )
#else
static int iarg_flex_strlen( s )
iargconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *iarg_flex_alloc( iarg_size_t size )
#else
static void *iarg_flex_alloc( size )
iarg_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *iarg_flex_realloc( void *ptr, iarg_size_t size )
#else
static void *iarg_flex_realloc( ptr, size )
void *ptr;
iarg_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void iarg_flex_free( void *ptr )
#else
static void iarg_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	iarglex();
	return 0;
	}
#endif
#line 90 "iarg.l"
