/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /data/mmti/CVSROOT/param/ipar_lex.c,v 1.3 2004/04/07 19:09:41 john Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define iparconst const
#else
#define iparconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN ipar_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((ipar_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE iparrestart( iparin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct ipar_buffer_state *YY_BUFFER_STATE;

extern int iparleng;
extern FILE *iparin, *iparout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		iparless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the iparless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define iparless(n) \
	do \
		{ \
		/* Undo effects of setting up ipartext. */ \
		*ipar_cp = ipar_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		ipar_c_buf_p = ipar_cp = ipar_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up ipartext again */ \
		} \
	while ( 0 )

#define unput(c) iparunput( c, ipartext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int ipar_size_t;


struct ipar_buffer_state
	{
	FILE *ipar_input_file;

	char *ipar_ch_buf;		/* input buffer */
	char *ipar_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	ipar_size_t ipar_buf_size;

	/* Number of characters read into ipar_ch_buf, not including EOB
	 * characters.
	 */
	int ipar_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int ipar_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int ipar_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int ipar_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int ipar_fill_buffer;

	int ipar_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via iparrestart()), so that the user can continue scanning by
	 * just pointing iparin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE ipar_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER ipar_current_buffer


/* ipar_hold_char holds the character lost when ipartext is formed. */
static char ipar_hold_char;

static int ipar_n_chars;		/* number of characters read into ipar_ch_buf */


int iparleng;

/* Points to current character in buffer. */
static char *ipar_c_buf_p = (char *) 0;
static int ipar_init = 1;		/* whether we need to initialize */
static int ipar_start = 0;	/* start state number */

/* Flag which is used to allow iparwrap()'s to do buffer switches
 * instead of setting up a fresh iparin.  A bit of a hack ...
 */
static int ipar_did_buffer_switch_on_eof;

void iparrestart YY_PROTO(( FILE *input_file ));

void ipar_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void ipar_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE ipar_create_buffer YY_PROTO(( FILE *file, int size ));
void ipar_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void ipar_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void ipar_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER ipar_flush_buffer( ipar_current_buffer )

YY_BUFFER_STATE ipar_scan_buffer YY_PROTO(( char *base, ipar_size_t size ));
YY_BUFFER_STATE ipar_scan_string YY_PROTO(( iparconst char *ipar_str ));
YY_BUFFER_STATE ipar_scan_bytes YY_PROTO(( iparconst char *bytes, int len ));

static void *ipar_flex_alloc YY_PROTO(( ipar_size_t ));
static void *ipar_flex_realloc YY_PROTO(( void *, ipar_size_t ));
static void ipar_flex_free YY_PROTO(( void * ));

#define ipar_new_buffer ipar_create_buffer

#define ipar_set_interactive(is_interactive) \
	{ \
	if ( ! ipar_current_buffer ) \
		ipar_current_buffer = ipar_create_buffer( iparin, YY_BUF_SIZE ); \
	ipar_current_buffer->ipar_is_interactive = is_interactive; \
	}

#define ipar_set_bol(at_bol) \
	{ \
	if ( ! ipar_current_buffer ) \
		ipar_current_buffer = ipar_create_buffer( iparin, YY_BUF_SIZE ); \
	ipar_current_buffer->ipar_at_bol = at_bol; \
	}

#define YY_AT_BOL() (ipar_current_buffer->ipar_at_bol)

typedef unsigned char YY_CHAR;
FILE *iparin = (FILE *) 0, *iparout = (FILE *) 0;
typedef int ipar_state_type;
extern char *ipartext;
#define ipartext_ptr ipartext

static ipar_state_type ipar_get_previous_state YY_PROTO(( void ));
static ipar_state_type ipar_try_NUL_trans YY_PROTO(( ipar_state_type current_state ));
static int ipar_get_next_buffer YY_PROTO(( void ));
static void ipar_fatal_error YY_PROTO(( iparconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up ipartext.
 */
#define YY_DO_BEFORE_ACTION \
	ipartext_ptr = ipar_bp; \
	iparleng = (int) (ipar_cp - ipar_bp); \
	ipar_hold_char = *ipar_cp; \
	*ipar_cp = '\0'; \
	ipar_c_buf_p = ipar_cp;

#define YY_NUM_RULES 18
#define YY_END_OF_BUFFER 19
static iparconst short int ipar_accept[92] =
    {   0,
        0,    0,    2,    2,    2,    2,    4,    4,    3,    3,
        7,    7,    8,    8,   19,   18,   15,   17,   16,   15,
       18,    2,    2,    2,    4,    4,    5,    6,    4,    4,
        3,    3,    3,    3,    3,    7,    7,    7,   11,    7,
       18,    7,    7,    8,    8,    8,   12,    8,   18,    8,
        8,   15,   17,   15,   14,    0,   13,    2,    2,    2,
        4,    4,    5,    6,    4,    4,    3,    3,    3,    3,
        7,    7,    7,    9,    7,    7,    7,    7,    8,    8,
        8,   10,    8,    8,    8,    8,    2,    2,    2,    1,
        0

    } ;

static iparconst int ipar_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    6,    1,
        1,    1,    1,    7,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    8,    1,    1,    1,    1,    1,    1,    9,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   10,   11,   12,   13,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static iparconst int ipar_meta[14] =
    {   0,
        1,    2,    3,    4,    1,    5,    6,    7,    1,    1,
        1,    1,    1
    } ;

static iparconst short int ipar_base[111] =
    {   0,
        0,    6,   12,   18,   24,   21,   34,   40,   46,   52,
       58,   65,   72,   79,   31,  302,   86,  302,  302,   88,
       27,    0,   90,   16,    0,   96,  302,  302,  101,  102,
        0,  108,    0,  110,   24,    0,  112,    0,  302,    0,
        0,  114,  115,    0,  122,    0,  302,    0,    0,  124,
      125,    0,  302,    0,  302,   21,  302,    0,  132,   12,
        0,    0,  302,  302,  138,  139,    0,  145,  147,   15,
        0,  149,    0,  302,  151,    0,  152,    0,    0,  159,
        0,  302,  161,    0,  162,    0,    4,    7,    0,    0,
      302,  170,  177,  184,  191,  198,  205,  212,  219,  226,

      233,  240,  247,  254,  261,  267,  274,  281,  287,  294
    } ;

static iparconst short int ipar_def[111] =
    {   0,
       92,   92,   93,   93,    4,    4,   94,   94,   95,   95,
       96,   96,   97,   97,   91,   91,   91,   91,   91,   91,
       98,   99,  100,   99,  101,  101,   91,   91,   26,  102,
      103,  103,  103,  103,  104,  105,  105,  105,   91,  105,
      106,  105,  107,  108,  108,  108,   91,  108,  109,  108,
      110,   17,   91,   20,   91,   98,   91,   99,  100,   99,
      101,   26,   91,   91,   26,  102,  103,  103,  103,  104,
      105,  105,  105,   91,  105,  105,  107,  105,  108,  108,
      108,   91,  108,  108,  110,  108,   99,   99,   99,   99,
        0,   91,   91,   91,   91,   91,   91,   91,   91,   91,

       91,   91,   91,   91,   91,   91,   91,   91,   91,   91
    } ;

static iparconst short int ipar_nxt[316] =
    {   0,
       91,   17,   18,   91,   91,   91,   19,   20,   18,   91,
       21,   90,   19,   17,   18,   89,   88,   57,   19,   20,
       18,   87,   23,   57,   19,   17,   57,   60,   22,   57,
       91,   24,   91,   91,   24,   26,   18,   27,   91,   28,
       19,   29,   18,   27,   30,   28,   19,   32,   18,   91,
       91,   91,   33,   34,   18,   91,   35,   91,   33,   37,
       38,   39,   91,   91,   40,   41,   42,   38,   39,   43,
       91,   40,   41,   45,   46,   91,   91,   47,   48,   49,
       50,   46,   91,   51,   47,   48,   49,   52,   53,   54,
       55,   56,   57,   91,   91,   91,   56,   62,   53,   63,

       91,   64,   65,   55,   57,   56,   91,   56,   56,   68,
       53,   69,   55,   72,   73,   75,   76,   78,   56,   91,
       91,   91,   56,   80,   81,   83,   84,   86,   91,   91,
       56,   91,   56,   56,   57,   91,   91,   91,   56,   65,
       55,   57,   56,   91,   56,   56,   68,   53,   69,   55,
       72,   73,   75,   76,   78,   56,   91,   91,   91,   56,
       80,   81,   83,   84,   86,   91,   91,   56,   91,   56,
       16,   16,   16,   16,   16,   16,   16,   22,   22,   22,
       22,   22,   22,   22,   25,   25,   25,   25,   25,   25,
       25,   31,   31,   31,   31,   31,   31,   31,   36,   36,

       36,   36,   36,   36,   36,   44,   44,   44,   44,   44,
       44,   44,   56,   56,   56,   56,   56,   56,   56,   58,
       91,   91,   58,   58,   91,   58,   59,   59,   59,   59,
       59,   59,   59,   61,   61,   91,   91,   91,   91,   61,
       66,   66,   66,   66,   66,   66,   66,   67,   67,   91,
       67,   67,   67,   67,   70,   70,   70,   70,   70,   70,
       70,   71,   71,   71,   91,   71,   71,   74,   74,   91,
       74,   74,   74,   74,   77,   77,   77,   77,   77,   77,
       77,   79,   79,   79,   79,   91,   79,   82,   82,   91,
       82,   82,   82,   82,   85,   85,   85,   85,   85,   85,

       85,   15,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91
    } ;

static iparconst short int ipar_chk[316] =
    {   0,
        0,    1,    1,    0,    0,    0,    1,    2,    2,    0,
        2,   89,    2,    3,    3,   88,   87,   70,    3,    4,
        4,   60,    4,   56,    4,    5,   35,   24,    5,   21,
       15,    6,    0,    0,    5,    7,    7,    7,    0,    7,
        7,    8,    8,    8,    8,    8,    8,    9,    9,    0,
        0,    0,    9,   10,   10,    0,   10,    0,   10,   11,
       11,   11,    0,    0,   11,   11,   12,   12,   12,   12,
        0,   12,   12,   13,   13,    0,    0,   13,   13,   13,
       14,   14,    0,   14,   14,   14,   14,   17,   17,   20,
       20,   23,   23,    0,    0,    0,   23,   26,   26,   26,

        0,   26,   29,   29,   30,   30,    0,   30,   30,   32,
       32,   34,   34,   37,   37,   42,   42,   43,   43,    0,
        0,    0,   43,   45,   45,   50,   50,   51,    0,    0,
       51,    0,   51,   59,   59,    0,    0,    0,   59,   65,
       65,   66,   66,    0,   66,   66,   68,   68,   69,   69,
       72,   72,   75,   75,   77,   77,    0,    0,    0,   77,
       80,   80,   83,   83,   85,    0,    0,   85,    0,   85,
       92,   92,   92,   92,   92,   92,   92,   93,   93,   93,
       93,   93,   93,   93,   94,   94,   94,   94,   94,   94,
       94,   95,   95,   95,   95,   95,   95,   95,   96,   96,

       96,   96,   96,   96,   96,   97,   97,   97,   97,   97,
       97,   97,   98,   98,   98,   98,   98,   98,   98,   99,
        0,    0,   99,   99,    0,   99,  100,  100,  100,  100,
      100,  100,  100,  101,  101,    0,    0,    0,    0,  101,
      102,  102,  102,  102,  102,  102,  102,  103,  103,    0,
      103,  103,  103,  103,  104,  104,  104,  104,  104,  104,
      104,  105,  105,  105,    0,  105,  105,  106,  106,    0,
      106,  106,  106,  106,  107,  107,  107,  107,  107,  107,
      107,  108,  108,  108,  108,    0,  108,  109,  109,    0,
      109,  109,  109,  109,  110,  110,  110,  110,  110,  110,

      110,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91
    } ;

static ipar_state_type ipar_last_accepting_state;
static char *ipar_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define iparmore() iparmore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *ipartext;
#line 1 "ipar.l"
#define INITIAL 0
#define NAME 1
#define TYPE 2
#define VALUE 3
#define LINE 4

#define DQUOTE 5
#define SQUOTE 6

#line 14 "ipar.l"
/* iparlex.l
**/

#include <stdlib.h>
#include <string.h>

#include "pfile.h"
#include "ipar.h"

#define YY_SKIP_YYWRAP

static char iparstring[SZ_PFLINE];

extern iparlineno;

#define StrCpy(res, str, len)	( strncpy((res=malloc(len + 1)), str, len),\
					res[len] = '\0', res)

/* This array and the field variable to cycle through the  context dependence
** of the current field that is expected.
**/
int	iparfields[7] = { NAME, TYPE, NAME, VALUE, VALUE, VALUE, VALUE };
int	iparfield = 0;
char	*iparinchar = NULL;


#define YY_USER_INIT	{ BEGIN(iparfields[iparfield = 0]);		}
/**
#define YY_USER_ACTION  { printf("field = %d, state = %d\n", iparfield, ipar_start); }
**/

#define P(x)	printf(x)

#define GetC(iparinchar)		(*(iparinchar++))
#undef  YY_INPUT
#define YY_INPUT(buffer, result, max)		\
	{					\
		 char ch;			\
		 ch = GetC(iparinchar);		\
		 if ( ch == '\\' ) {		\
		    ch = GetC(iparinchar);		\
		    if ( ch == '\n' ) ch = ' ';	\
		 }				\
		 if ( ch == '\0' )		\
		    result = 0;			\
		 else {				\
		    *buffer = ch;		\
		     result = 1;		\
		 }				\
	}

/* default iargwrap function - always treat EOF as an EOF */
int iparwrap() {
	return 1;
}
#line 528 "lex.ipar.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int iparwrap YY_PROTO(( void ));
#else
extern int iparwrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void iparunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef ipartext_ptr
static void ipar_flex_strncpy YY_PROTO(( char *, iparconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int ipar_flex_strlen YY_PROTO(( iparconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int iparinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int ipar_start_stack_ptr = 0;
static int ipar_start_stack_depth = 0;
static int *ipar_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void ipar_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void ipar_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int ipar_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( ipartext, iparleng, 1, iparout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( ipar_current_buffer->ipar_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( iparin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( iparin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, iparin )) == 0) \
		  && ferror( iparin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "iparterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef iparterminate
#define iparterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) ipar_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int iparlex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after ipartext and iparleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( iparleng > 0 ) \
		ipar_current_buffer->ipar_at_bol = \
				(ipartext[iparleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register ipar_state_type ipar_current_state;
	register char *ipar_cp, *ipar_bp;
	register int ipar_act;

#line 72 "ipar.l"

#line 684 "lex.ipar.c"

	if ( ipar_init )
		{
		ipar_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! ipar_start )
			ipar_start = 1;	/* first start state */

		if ( ! iparin )
			iparin = stdin;

		if ( ! iparout )
			iparout = stdout;

		if ( ! ipar_current_buffer )
			ipar_current_buffer =
				ipar_create_buffer( iparin, YY_BUF_SIZE );

		ipar_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		ipar_cp = ipar_c_buf_p;

		/* Support of ipartext. */
		*ipar_cp = ipar_hold_char;

		/* ipar_bp points to the position in ipar_ch_buf of the start of
		 * the current run.
		 */
		ipar_bp = ipar_cp;

		ipar_current_state = ipar_start;
		ipar_current_state += YY_AT_BOL();
ipar_match:
		do
			{
			register YY_CHAR ipar_c = ipar_ec[YY_SC_TO_UI(*ipar_cp)];
			if ( ipar_accept[ipar_current_state] )
				{
				ipar_last_accepting_state = ipar_current_state;
				ipar_last_accepting_cpos = ipar_cp;
				}
			while ( ipar_chk[ipar_base[ipar_current_state] + ipar_c] != ipar_current_state )
				{
				ipar_current_state = (int) ipar_def[ipar_current_state];
				if ( ipar_current_state >= 92 )
					ipar_c = ipar_meta[(unsigned int) ipar_c];
				}
			ipar_current_state = ipar_nxt[ipar_base[ipar_current_state] + (unsigned int) ipar_c];
			++ipar_cp;
			}
		while ( ipar_base[ipar_current_state] != 302 );

ipar_find_action:
		ipar_act = ipar_accept[ipar_current_state];
		if ( ipar_act == 0 )
			{ /* have to back up */
			ipar_cp = ipar_last_accepting_cpos;
			ipar_current_state = ipar_last_accepting_state;
			ipar_act = ipar_accept[ipar_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( ipar_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*ipar_cp = ipar_hold_char;
			ipar_cp = ipar_last_accepting_cpos;
			ipar_current_state = ipar_last_accepting_state;
			goto ipar_find_action;

case 1:
YY_RULE_SETUP
#line 73 "ipar.l"
{	StrCpy(iparlval.stri, ipartext, iparleng);	return T_struct;	}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 74 "ipar.l"
{	StrCpy(iparlval.stri, ipartext, iparleng);	return T_word;		}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 76 "ipar.l"
{	StrCpy(iparlval.stri, ipartext, iparleng);	return T_line;		}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 78 "ipar.l"
{	StrCpy(iparlval.stri, ipartext, iparleng);	return T_word;		}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 80 "ipar.l"
{	iparstring[0] = '\0';  BEGIN(DQUOTE);  		}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 81 "ipar.l"
{	iparstring[0] = '\0';  BEGIN(SQUOTE);		}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 83 "ipar.l"
{ 	strncat(iparstring, ipartext, iparleng);              }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 84 "ipar.l"
{ 	strncat(iparstring, ipartext, iparleng);              }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 85 "ipar.l"
{	strncat(iparstring, ipartext, iparleng);              }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 86 "ipar.l"
{	strncat(iparstring, ipartext, iparleng);              }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 87 "ipar.l"
{	BEGIN(VALUE);
                        StrCpy(iparlval.stri, iparstring, strlen(iparstring) + 1); return T_word; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 89 "ipar.l"
{	BEGIN(VALUE);
                        StrCpy(iparlval.stri, iparstring, strlen(iparstring) + 1); return T_word; }
	YY_BREAK
case 13:
*ipar_cp = ipar_hold_char; /* undo effects of setting up ipartext */
ipar_c_buf_p = ipar_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up ipartext again */
YY_RULE_SETUP
#line 92 "ipar.l"
{
			char	*value;
			int	mode = 0;

		  iparlval.param = ParamCreate(strdup("#")
				, CommentType
				, &mode, StrCpy(value, ipartext, iparleng)
				, NULL);

		  return T_comment;
		}
	YY_BREAK
case 14:
*ipar_cp = ipar_hold_char; /* undo effects of setting up ipartext */
ipar_c_buf_p = ipar_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up ipartext again */
YY_RULE_SETUP
#line 104 "ipar.l"
{
			char	*value;
			int	mode = 0;
		  iparlval.param = ParamCreate(strdup("")
				, CommentType
				, &mode, StrCpy(value, ipartext, iparleng)
				, NULL);

		  return T_comment;
		}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 114 "ipar.l"
{	;	}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 115 "ipar.l"
{ 	BEGIN(iparfields[++iparfield]);		return ','; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 116 "ipar.l"
{
			iparlineno++;
			BEGIN(iparfields[iparfield = 0]);		return T_nl;
		}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 122 "ipar.l"
ECHO;
	YY_BREAK
#line 888 "lex.ipar.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(NAME):
case YY_STATE_EOF(TYPE):
case YY_STATE_EOF(VALUE):
case YY_STATE_EOF(LINE):
case YY_STATE_EOF(DQUOTE):
case YY_STATE_EOF(SQUOTE):
	iparterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int ipar_amount_of_matched_text = (int) (ipar_cp - ipartext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*ipar_cp = ipar_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( ipar_current_buffer->ipar_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed iparin at a new source and called
			 * iparlex().  If so, then we have to assure
			 * consistency between ipar_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			ipar_n_chars = ipar_current_buffer->ipar_n_chars;
			ipar_current_buffer->ipar_input_file = iparin;
			ipar_current_buffer->ipar_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for ipar_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since ipar_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( ipar_c_buf_p <= &ipar_current_buffer->ipar_ch_buf[ipar_n_chars] )
			{ /* This was really a NUL. */
			ipar_state_type ipar_next_state;

			ipar_c_buf_p = ipartext_ptr + ipar_amount_of_matched_text;

			ipar_current_state = ipar_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * ipar_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			ipar_next_state = ipar_try_NUL_trans( ipar_current_state );

			ipar_bp = ipartext_ptr + YY_MORE_ADJ;

			if ( ipar_next_state )
				{
				/* Consume the NUL. */
				ipar_cp = ++ipar_c_buf_p;
				ipar_current_state = ipar_next_state;
				goto ipar_match;
				}

			else
				{
				ipar_cp = ipar_c_buf_p;
				goto ipar_find_action;
				}
			}

		else switch ( ipar_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				ipar_did_buffer_switch_on_eof = 0;

				if ( iparwrap() )
					{
					/* Note: because we've taken care in
					 * ipar_get_next_buffer() to have set up
					 * ipartext, we can now set up
					 * ipar_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					ipar_c_buf_p = ipartext_ptr + YY_MORE_ADJ;

					ipar_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! ipar_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				ipar_c_buf_p =
					ipartext_ptr + ipar_amount_of_matched_text;

				ipar_current_state = ipar_get_previous_state();

				ipar_cp = ipar_c_buf_p;
				ipar_bp = ipartext_ptr + YY_MORE_ADJ;
				goto ipar_match;

			case EOB_ACT_LAST_MATCH:
				ipar_c_buf_p =
				&ipar_current_buffer->ipar_ch_buf[ipar_n_chars];

				ipar_current_state = ipar_get_previous_state();

				ipar_cp = ipar_c_buf_p;
				ipar_bp = ipartext_ptr + YY_MORE_ADJ;
				goto ipar_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of iparlex */


/* ipar_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int ipar_get_next_buffer()
	{
	register char *dest = ipar_current_buffer->ipar_ch_buf;
	register char *source = ipartext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( ipar_c_buf_p > &ipar_current_buffer->ipar_ch_buf[ipar_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( ipar_current_buffer->ipar_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( ipar_c_buf_p - ipartext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (ipar_c_buf_p - ipartext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( ipar_current_buffer->ipar_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		ipar_current_buffer->ipar_n_chars = ipar_n_chars = 0;

	else
		{
		int num_to_read =
			ipar_current_buffer->ipar_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = ipar_current_buffer;

			int ipar_c_buf_p_offset =
				(int) (ipar_c_buf_p - b->ipar_ch_buf);

			if ( b->ipar_is_our_buffer )
				{
				int new_size = b->ipar_buf_size * 2;

				if ( new_size <= 0 )
					b->ipar_buf_size += b->ipar_buf_size / 8;
				else
					b->ipar_buf_size *= 2;

				b->ipar_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					ipar_flex_realloc( (void *) b->ipar_ch_buf,
							 b->ipar_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->ipar_ch_buf = 0;

			if ( ! b->ipar_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			ipar_c_buf_p = &b->ipar_ch_buf[ipar_c_buf_p_offset];

			num_to_read = ipar_current_buffer->ipar_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&ipar_current_buffer->ipar_ch_buf[number_to_move]),
			ipar_n_chars, num_to_read );

		ipar_current_buffer->ipar_n_chars = ipar_n_chars;
		}

	if ( ipar_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			iparrestart( iparin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			ipar_current_buffer->ipar_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	ipar_n_chars += number_to_move;
	ipar_current_buffer->ipar_ch_buf[ipar_n_chars] = YY_END_OF_BUFFER_CHAR;
	ipar_current_buffer->ipar_ch_buf[ipar_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	ipartext_ptr = &ipar_current_buffer->ipar_ch_buf[0];

	return ret_val;
	}


/* ipar_get_previous_state - get the state just before the EOB char was reached */

static ipar_state_type ipar_get_previous_state()
	{
	register ipar_state_type ipar_current_state;
	register char *ipar_cp;

	ipar_current_state = ipar_start;
	ipar_current_state += YY_AT_BOL();

	for ( ipar_cp = ipartext_ptr + YY_MORE_ADJ; ipar_cp < ipar_c_buf_p; ++ipar_cp )
		{
		register YY_CHAR ipar_c = (*ipar_cp ? ipar_ec[YY_SC_TO_UI(*ipar_cp)] : 1);
		if ( ipar_accept[ipar_current_state] )
			{
			ipar_last_accepting_state = ipar_current_state;
			ipar_last_accepting_cpos = ipar_cp;
			}
		while ( ipar_chk[ipar_base[ipar_current_state] + ipar_c] != ipar_current_state )
			{
			ipar_current_state = (int) ipar_def[ipar_current_state];
			if ( ipar_current_state >= 92 )
				ipar_c = ipar_meta[(unsigned int) ipar_c];
			}
		ipar_current_state = ipar_nxt[ipar_base[ipar_current_state] + (unsigned int) ipar_c];
		}

	return ipar_current_state;
	}


/* ipar_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = ipar_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static ipar_state_type ipar_try_NUL_trans( ipar_state_type ipar_current_state )
#else
static ipar_state_type ipar_try_NUL_trans( ipar_current_state )
ipar_state_type ipar_current_state;
#endif
	{
	register int ipar_is_jam;
	register char *ipar_cp = ipar_c_buf_p;

	register YY_CHAR ipar_c = 1;
	if ( ipar_accept[ipar_current_state] )
		{
		ipar_last_accepting_state = ipar_current_state;
		ipar_last_accepting_cpos = ipar_cp;
		}
	while ( ipar_chk[ipar_base[ipar_current_state] + ipar_c] != ipar_current_state )
		{
		ipar_current_state = (int) ipar_def[ipar_current_state];
		if ( ipar_current_state >= 92 )
			ipar_c = ipar_meta[(unsigned int) ipar_c];
		}
	ipar_current_state = ipar_nxt[ipar_base[ipar_current_state] + (unsigned int) ipar_c];
	ipar_is_jam = (ipar_current_state == 91);

	return ipar_is_jam ? 0 : ipar_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void iparunput( int c, register char *ipar_bp )
#else
static void iparunput( c, ipar_bp )
int c;
register char *ipar_bp;
#endif
	{
	register char *ipar_cp = ipar_c_buf_p;

	/* undo effects of setting up ipartext */
	*ipar_cp = ipar_hold_char;

	if ( ipar_cp < ipar_current_buffer->ipar_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = ipar_n_chars + 2;
		register char *dest = &ipar_current_buffer->ipar_ch_buf[
					ipar_current_buffer->ipar_buf_size + 2];
		register char *source =
				&ipar_current_buffer->ipar_ch_buf[number_to_move];

		while ( source > ipar_current_buffer->ipar_ch_buf )
			*--dest = *--source;

		ipar_cp += (int) (dest - source);
		ipar_bp += (int) (dest - source);
		ipar_current_buffer->ipar_n_chars =
			ipar_n_chars = ipar_current_buffer->ipar_buf_size;

		if ( ipar_cp < ipar_current_buffer->ipar_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--ipar_cp = (char) c;


	ipartext_ptr = ipar_bp;
	ipar_hold_char = *ipar_cp;
	ipar_c_buf_p = ipar_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int iparinput()
#else
static int input()
#endif
	{
	int c;

	*ipar_c_buf_p = ipar_hold_char;

	if ( *ipar_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* ipar_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( ipar_c_buf_p < &ipar_current_buffer->ipar_ch_buf[ipar_n_chars] )
			/* This was really a NUL. */
			*ipar_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = ipar_c_buf_p - ipartext_ptr;
			++ipar_c_buf_p;

			switch ( ipar_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because ipar_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					iparrestart( iparin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( iparwrap() )
						return EOF;

					if ( ! ipar_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return iparinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					ipar_c_buf_p = ipartext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) ipar_c_buf_p;	/* cast for 8-bit char's */
	*ipar_c_buf_p = '\0';	/* preserve ipartext */
	ipar_hold_char = *++ipar_c_buf_p;

	ipar_current_buffer->ipar_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void iparrestart( FILE *input_file )
#else
void iparrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! ipar_current_buffer )
		ipar_current_buffer = ipar_create_buffer( iparin, YY_BUF_SIZE );

	ipar_init_buffer( ipar_current_buffer, input_file );
	ipar_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void ipar_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void ipar_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( ipar_current_buffer == new_buffer )
		return;

	if ( ipar_current_buffer )
		{
		/* Flush out information for old buffer. */
		*ipar_c_buf_p = ipar_hold_char;
		ipar_current_buffer->ipar_buf_pos = ipar_c_buf_p;
		ipar_current_buffer->ipar_n_chars = ipar_n_chars;
		}

	ipar_current_buffer = new_buffer;
	ipar_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (iparwrap()) processing, but the only time this flag
	 * is looked at is after iparwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	ipar_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void ipar_load_buffer_state( void )
#else
void ipar_load_buffer_state()
#endif
	{
	ipar_n_chars = ipar_current_buffer->ipar_n_chars;
	ipartext_ptr = ipar_c_buf_p = ipar_current_buffer->ipar_buf_pos;
	iparin = ipar_current_buffer->ipar_input_file;
	ipar_hold_char = *ipar_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE ipar_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE ipar_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) ipar_flex_alloc( sizeof( struct ipar_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ipar_create_buffer()" );

	b->ipar_buf_size = size;

	/* ipar_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->ipar_ch_buf = (char *) ipar_flex_alloc( b->ipar_buf_size + 2 );
	if ( ! b->ipar_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in ipar_create_buffer()" );

	b->ipar_is_our_buffer = 1;

	ipar_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void ipar_delete_buffer( YY_BUFFER_STATE b )
#else
void ipar_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == ipar_current_buffer )
		ipar_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->ipar_is_our_buffer )
		ipar_flex_free( (void *) b->ipar_ch_buf );

	ipar_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void ipar_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void ipar_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	ipar_flush_buffer( b );

	b->ipar_input_file = file;
	b->ipar_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->ipar_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->ipar_is_interactive = 0;
#else
	b->ipar_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void ipar_flush_buffer( YY_BUFFER_STATE b )
#else
void ipar_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->ipar_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->ipar_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->ipar_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->ipar_buf_pos = &b->ipar_ch_buf[0];

	b->ipar_at_bol = 1;
	b->ipar_buffer_status = YY_BUFFER_NEW;

	if ( b == ipar_current_buffer )
		ipar_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE ipar_scan_buffer( char *base, ipar_size_t size )
#else
YY_BUFFER_STATE ipar_scan_buffer( base, size )
char *base;
ipar_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) ipar_flex_alloc( sizeof( struct ipar_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ipar_scan_buffer()" );

	b->ipar_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->ipar_buf_pos = b->ipar_ch_buf = base;
	b->ipar_is_our_buffer = 0;
	b->ipar_input_file = 0;
	b->ipar_n_chars = b->ipar_buf_size;
	b->ipar_is_interactive = 0;
	b->ipar_at_bol = 1;
	b->ipar_fill_buffer = 0;
	b->ipar_buffer_status = YY_BUFFER_NEW;

	ipar_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE ipar_scan_string( iparconst char *ipar_str )
#else
YY_BUFFER_STATE ipar_scan_string( ipar_str )
iparconst char *ipar_str;
#endif
	{
	int len;
	for ( len = 0; ipar_str[len]; ++len )
		;

	return ipar_scan_bytes( ipar_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE ipar_scan_bytes( iparconst char *bytes, int len )
#else
YY_BUFFER_STATE ipar_scan_bytes( bytes, len )
iparconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	ipar_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) ipar_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in ipar_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = ipar_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in ipar_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->ipar_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void ipar_push_state( int new_state )
#else
static void ipar_push_state( new_state )
int new_state;
#endif
	{
	if ( ipar_start_stack_ptr >= ipar_start_stack_depth )
		{
		ipar_size_t new_size;

		ipar_start_stack_depth += YY_START_STACK_INCR;
		new_size = ipar_start_stack_depth * sizeof( int );

		if ( ! ipar_start_stack )
			ipar_start_stack = (int *) ipar_flex_alloc( new_size );

		else
			ipar_start_stack = (int *) ipar_flex_realloc(
					(void *) ipar_start_stack, new_size );

		if ( ! ipar_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	ipar_start_stack[ipar_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void ipar_pop_state()
	{
	if ( --ipar_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(ipar_start_stack[ipar_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int ipar_top_state()
	{
	return ipar_start_stack[ipar_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void ipar_fatal_error( iparconst char msg[] )
#else
static void ipar_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine iparless() so it works in section 3 code. */

#undef iparless
#define iparless(n) \
	do \
		{ \
		/* Undo effects of setting up ipartext. */ \
		ipartext[iparleng] = ipar_hold_char; \
		ipar_c_buf_p = ipartext + n; \
		ipar_hold_char = *ipar_c_buf_p; \
		*ipar_c_buf_p = '\0'; \
		iparleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef ipartext_ptr
#ifdef YY_USE_PROTOS
static void ipar_flex_strncpy( char *s1, iparconst char *s2, int n )
#else
static void ipar_flex_strncpy( s1, s2, n )
char *s1;
iparconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int ipar_flex_strlen( iparconst char *s )
#else
static int ipar_flex_strlen( s )
iparconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *ipar_flex_alloc( ipar_size_t size )
#else
static void *ipar_flex_alloc( size )
ipar_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *ipar_flex_realloc( void *ptr, ipar_size_t size )
#else
static void *ipar_flex_realloc( ptr, size )
void *ptr;
ipar_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void ipar_flex_free( void *ptr )
#else
static void ipar_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	iparlex();
	return 0;
	}
#endif
#line 122 "ipar.l"


/* Lexical tie called by grammar
**/
void iparbegin(state)
    int state;
{
	BEGIN(state);

}


iparreparse()
{
	BEGIN(iparfields[iparfield = 0]);
}
