HEADERS = find.h  history.h  iarg.h  ipar.h  list.h  parambind.h  parameter.h  pargs.h  pfile.h  ptemplat.h  putil.h  range.h
OBJECTS = boolean.o cbinding.o clfg.o comment.o f77.o filetype.o find.o gcur.o getenum.o getfile.o gtype.o iarg_lex.o iarg_yac.o imcur.o inclass.o integer.o ipar_lex.o ipar_yac.o iraf.o listhook.o macros.o mode.o parament.o parameter.o paramset.o paramstropen.o pbase.o pfile.o psets.o ptemplat.o putil.o range.o rdbf.o rdb_lex.o readline.o real.o string.o struct.o tmatch.o type.o uclxfile.o uerget.o unxfbind.o
TARGET  = libparam.a
MAKE_TARGET = $(MAKE_LIB_TARGET)
include ../../include/Makefile.inc
