/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /data/mmti/CVSROOT/param/rdb_lex.c,v 1.3 2004/04/07 19:09:41 john Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define rdbconst const
#else
#define rdbconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN rdb_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((rdb_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE rdbrestart( rdbin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct rdb_buffer_state *YY_BUFFER_STATE;

extern int rdbleng;
extern FILE *rdbin, *rdbout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		rdbless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the rdbless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define rdbless(n) \
	do \
		{ \
		/* Undo effects of setting up rdbtext. */ \
		*rdb_cp = rdb_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		rdb_c_buf_p = rdb_cp = rdb_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up rdbtext again */ \
		} \
	while ( 0 )

#define unput(c) rdbunput( c, rdbtext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int rdb_size_t;


struct rdb_buffer_state
	{
	FILE *rdb_input_file;

	char *rdb_ch_buf;		/* input buffer */
	char *rdb_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	rdb_size_t rdb_buf_size;

	/* Number of characters read into rdb_ch_buf, not including EOB
	 * characters.
	 */
	int rdb_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int rdb_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int rdb_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int rdb_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int rdb_fill_buffer;

	int rdb_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via rdbrestart()), so that the user can continue scanning by
	 * just pointing rdbin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE rdb_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER rdb_current_buffer


/* rdb_hold_char holds the character lost when rdbtext is formed. */
static char rdb_hold_char;

static int rdb_n_chars;		/* number of characters read into rdb_ch_buf */


int rdbleng;

/* Points to current character in buffer. */
static char *rdb_c_buf_p = (char *) 0;
static int rdb_init = 1;		/* whether we need to initialize */
static int rdb_start = 0;	/* start state number */

/* Flag which is used to allow rdbwrap()'s to do buffer switches
 * instead of setting up a fresh rdbin.  A bit of a hack ...
 */
static int rdb_did_buffer_switch_on_eof;

void rdbrestart YY_PROTO(( FILE *input_file ));

void rdb_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void rdb_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE rdb_create_buffer YY_PROTO(( FILE *file, int size ));
void rdb_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void rdb_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void rdb_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER rdb_flush_buffer( rdb_current_buffer )

YY_BUFFER_STATE rdb_scan_buffer YY_PROTO(( char *base, rdb_size_t size ));
YY_BUFFER_STATE rdb_scan_string YY_PROTO(( rdbconst char *rdb_str ));
YY_BUFFER_STATE rdb_scan_bytes YY_PROTO(( rdbconst char *bytes, int len ));

static void *rdb_flex_alloc YY_PROTO(( rdb_size_t ));
static void *rdb_flex_realloc YY_PROTO(( void *, rdb_size_t ));
static void rdb_flex_free YY_PROTO(( void * ));

#define rdb_new_buffer rdb_create_buffer

#define rdb_set_interactive(is_interactive) \
	{ \
	if ( ! rdb_current_buffer ) \
		rdb_current_buffer = rdb_create_buffer( rdbin, YY_BUF_SIZE ); \
	rdb_current_buffer->rdb_is_interactive = is_interactive; \
	}

#define rdb_set_bol(at_bol) \
	{ \
	if ( ! rdb_current_buffer ) \
		rdb_current_buffer = rdb_create_buffer( rdbin, YY_BUF_SIZE ); \
	rdb_current_buffer->rdb_at_bol = at_bol; \
	}

#define YY_AT_BOL() (rdb_current_buffer->rdb_at_bol)

typedef unsigned char YY_CHAR;
FILE *rdbin = (FILE *) 0, *rdbout = (FILE *) 0;
typedef int rdb_state_type;
extern char *rdbtext;
#define rdbtext_ptr rdbtext

static rdb_state_type rdb_get_previous_state YY_PROTO(( void ));
static rdb_state_type rdb_try_NUL_trans YY_PROTO(( rdb_state_type current_state ));
static int rdb_get_next_buffer YY_PROTO(( void ));
static void rdb_fatal_error YY_PROTO(( rdbconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up rdbtext.
 */
#define YY_DO_BEFORE_ACTION \
	rdbtext_ptr = rdb_bp; \
	rdbleng = (int) (rdb_cp - rdb_bp); \
	rdb_hold_char = *rdb_cp; \
	*rdb_cp = '\0'; \
	rdb_c_buf_p = rdb_cp;

#define YY_NUM_RULES 15
#define YY_END_OF_BUFFER 16
static rdbconst short int rdb_accept[47] =
    {   0,
        0,    0,    0,    0,    0,    0,   16,   14,   13,    8,
       14,   14,   14,   14,   14,   15,   13,   10,    9,   11,
       12,    0,    0,    0,    0,    0,    0,    0,    9,   11,
        6,    5,    0,    0,    0,    0,    0,    2,    1,    0,
        4,    0,    0,    3,    7,    0
    } ;

static rdbconst int rdb_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    1,    1,    6,

        7,    1,    1,    1,    8,    1,    1,    9,   10,   11,
       12,   13,    1,   14,    1,   15,   16,   17,    1,   18,
       19,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static rdbconst int rdb_meta[20] =
    {   0,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1
    } ;

static rdbconst short int rdb_base[51] =
    {   0,
        0,   16,   32,   35,    2,    4,   60,   61,   61,   61,
       35,   54,   44,   38,   51,   61,   61,   61,   51,    0,
       61,   36,   35,   39,   34,   30,   28,   23,   26,    0,
       61,   61,   21,   18,   14,   16,    6,   61,   61,    8,
       61,   13,    1,   61,   61,   61,   47,   49,   51,    0
    } ;

static rdbconst short int rdb_def[51] =
    {   0,
       47,   47,   48,   48,   49,   49,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   50,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   50,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,    0,   46,   46,   46,   46
    } ;

static rdbconst short int rdb_nxt[81] =
    {   0,
       30,    9,   10,   17,   21,   17,   21,   46,   46,   11,
       12,   46,   13,   46,   14,   45,   15,    9,   10,   44,
       43,   42,   41,   40,   39,   11,   12,   38,   13,   29,
       14,   37,   15,   17,   18,   19,   17,   18,   19,   22,
       36,   35,   23,   34,   33,   32,   24,    8,    8,   16,
       16,   20,   20,   31,   29,   28,   27,   26,   25,   46,
        7,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46
    } ;

static rdbconst short int rdb_chk[81] =
    {   0,
       50,    1,    1,    5,    5,    6,    6,    0,    0,    1,
        1,    0,    1,    0,    1,   43,    1,    2,    2,   42,
       40,   37,   36,   35,   34,    2,    2,   33,    2,   29,
        2,   28,    2,    3,    3,    3,    4,    4,    4,   11,
       27,   26,   11,   25,   24,   23,   11,   47,   47,   48,
       48,   49,   49,   22,   19,   15,   14,   13,   12,    7,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46
    } ;

static rdb_state_type rdb_last_accepting_state;
static char *rdb_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define rdbmore() rdbmore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *rdbtext;
#line 1 "rdb.l"
#define INITIAL 0
#define WIDTH 1
#define BODY 2

#line 6 "rdb.l"
/* rdbpar.l
**/

#include <string.h>
#include <stdlib.h>

#include "pfile.h"
#include "ptemplat.h"
#include "parameter.h"

extern int *String2Mode();


#define YY_SKIP_YYWRAP

#define StrCpy(res, str, len)	( strncpy((res=malloc(len + 1)), str, len),\
					res[len] = '\0', res)

/* This array and the field variable to cycle through the  context dependence
** of the current field that is expected.
**/
static int	fields[7];
static int	widths[7];
static int	field = 0;
static Parameter *p;
static ParamList *result;

#define YY_USER_INIT	{ BEGIN(fields[field = 0]);		}
/**
#define YY_USER_ACTION  { printf("field = %d, state = %d\n", field, rdb_start); }
**/

#define P	printf

#undef  YY_INPUT
#define YY_INPUT(buffer, result, max)					\
	{								\
		result = fread(buffer, 1, max, (FILE *) rdbin);		\
	}

#define NAME	0
#define TYPE	1
#define MODE	2
#define VALUE	3
#define MIN	4
#define MAX	5
#define PROMPT	6

/* default rdbwrap function - always treat EOF as an EOF */
int rdbwrap() {
	return 1;
}
#line 446 "lex.rdb.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int rdbwrap YY_PROTO(( void ));
#else
extern int rdbwrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void rdbunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef rdbtext_ptr
static void rdb_flex_strncpy YY_PROTO(( char *, rdbconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int rdb_flex_strlen YY_PROTO(( rdbconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int rdbinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int rdb_start_stack_ptr = 0;
static int rdb_start_stack_depth = 0;
static int *rdb_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void rdb_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void rdb_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int rdb_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( rdbtext, rdbleng, 1, rdbout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( rdb_current_buffer->rdb_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( rdbin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( rdbin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, rdbin )) == 0) \
		  && ferror( rdbin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "rdbterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef rdbterminate
#define rdbterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) rdb_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int rdblex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after rdbtext and rdbleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register rdb_state_type rdb_current_state;
	register char *rdb_cp, *rdb_bp;
	register int rdb_act;

#line 61 "rdb.l"


#line 600 "lex.rdb.c"

	if ( rdb_init )
		{
		rdb_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! rdb_start )
			rdb_start = 1;	/* first start state */

		if ( ! rdbin )
			rdbin = stdin;

		if ( ! rdbout )
			rdbout = stdout;

		if ( ! rdb_current_buffer )
			rdb_current_buffer =
				rdb_create_buffer( rdbin, YY_BUF_SIZE );

		rdb_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		rdb_cp = rdb_c_buf_p;

		/* Support of rdbtext. */
		*rdb_cp = rdb_hold_char;

		/* rdb_bp points to the position in rdb_ch_buf of the start of
		 * the current run.
		 */
		rdb_bp = rdb_cp;

		rdb_current_state = rdb_start;
rdb_match:
		do
			{
			register YY_CHAR rdb_c = rdb_ec[YY_SC_TO_UI(*rdb_cp)];
			if ( rdb_accept[rdb_current_state] )
				{
				rdb_last_accepting_state = rdb_current_state;
				rdb_last_accepting_cpos = rdb_cp;
				}
			while ( rdb_chk[rdb_base[rdb_current_state] + rdb_c] != rdb_current_state )
				{
				rdb_current_state = (int) rdb_def[rdb_current_state];
				if ( rdb_current_state >= 47 )
					rdb_c = rdb_meta[(unsigned int) rdb_c];
				}
			rdb_current_state = rdb_nxt[rdb_base[rdb_current_state] + (unsigned int) rdb_c];
			++rdb_cp;
			}
		while ( rdb_base[rdb_current_state] != 61 );

rdb_find_action:
		rdb_act = rdb_accept[rdb_current_state];
		if ( rdb_act == 0 )
			{ /* have to back up */
			rdb_cp = rdb_last_accepting_cpos;
			rdb_current_state = rdb_last_accepting_state;
			rdb_act = rdb_accept[rdb_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( rdb_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*rdb_cp = rdb_hold_char;
			rdb_cp = rdb_last_accepting_cpos;
			rdb_current_state = rdb_last_accepting_state;
			goto rdb_find_action;

case 1:
YY_RULE_SETUP
#line 63 "rdb.l"
{	fields[field] = NAME;		}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 "rdb.l"
{	fields[field] = MODE;		}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 65 "rdb.l"
{	fields[field] = VALUE;		}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 66 "rdb.l"
{	fields[field] = TYPE;		}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 67 "rdb.l"
{	fields[field] = MIN;		}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 68 "rdb.l"
{	fields[field] = MAX;		}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 69 "rdb.l"
{	fields[field] = PROMPT;		}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 70 "rdb.l"
{
			if ( fields[NAME] ) {
				field = 0;
				BEGIN(WIDTH);
			}
		}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 77 "rdb.l"
{	widths[field] = strlen(rdbtext);	}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 78 "rdb.l"
{	field = 0;
			BEGIN(BODY);
		}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 82 "rdb.l"
{	
  switch ( fields[field] ) {
    char *s;
    int  mode;

  case NAME:
    p = ParamName(p, StrCpy(s, rdbtext, rdbleng)); break;

  case TYPE:
    if ( p )
      if ( !ParamType(p, String2Type(rdbtext))) {
	paramerr(0, "rdb parser", p->pname);
	free(p);
      }
    break;

  case MODE:
    if ( p ) 
      if ( !ParamMode(p, String2Mode(rdbtext, &mode))) {
	paramerr(0, "rdb parser", p->pname);
	free(p);
      }
    break;

  case VALUE:
    if ( p ) p = ParamValue(p, StringType, StrCpy(s, rdbtext, rdbleng)); break;
  case MIN:
    if ( p ) p = ParamMin(p, StringType, StrCpy(s, rdbtext, rdbleng)); break;
  case MAX:
    if ( p ) p = ParamMax(p, StringType, StrCpy(s, rdbtext, rdbleng)); break;
  case PROMPT:
    if ( p ) p = ParamPrompt(p, StrCpy(s, rdbtext, rdbleng)); break;
			}
		}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 116 "rdb.l"
{	if ( p && (p->pvalue.value==NULL) )
				VNewValue(&p->pvalue, "", StringType);

			if ( p )
			  result = PListAdd(result, p);

			field = 0;
			p = NULL;
		}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 125 "rdb.l"
{	field++;		}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(WIDTH):
case YY_STATE_EOF(BODY):
#line 127 "rdb.l"
{ return 1;	};
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 128 "rdb.l"
{ return 0; 	}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 129 "rdb.l"
ECHO;
	YY_BREAK
#line 812 "lex.rdb.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int rdb_amount_of_matched_text = (int) (rdb_cp - rdbtext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*rdb_cp = rdb_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( rdb_current_buffer->rdb_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed rdbin at a new source and called
			 * rdblex().  If so, then we have to assure
			 * consistency between rdb_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			rdb_n_chars = rdb_current_buffer->rdb_n_chars;
			rdb_current_buffer->rdb_input_file = rdbin;
			rdb_current_buffer->rdb_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for rdb_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since rdb_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( rdb_c_buf_p <= &rdb_current_buffer->rdb_ch_buf[rdb_n_chars] )
			{ /* This was really a NUL. */
			rdb_state_type rdb_next_state;

			rdb_c_buf_p = rdbtext_ptr + rdb_amount_of_matched_text;

			rdb_current_state = rdb_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * rdb_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			rdb_next_state = rdb_try_NUL_trans( rdb_current_state );

			rdb_bp = rdbtext_ptr + YY_MORE_ADJ;

			if ( rdb_next_state )
				{
				/* Consume the NUL. */
				rdb_cp = ++rdb_c_buf_p;
				rdb_current_state = rdb_next_state;
				goto rdb_match;
				}

			else
				{
				rdb_cp = rdb_c_buf_p;
				goto rdb_find_action;
				}
			}

		else switch ( rdb_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				rdb_did_buffer_switch_on_eof = 0;

				if ( rdbwrap() )
					{
					/* Note: because we've taken care in
					 * rdb_get_next_buffer() to have set up
					 * rdbtext, we can now set up
					 * rdb_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					rdb_c_buf_p = rdbtext_ptr + YY_MORE_ADJ;

					rdb_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! rdb_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				rdb_c_buf_p =
					rdbtext_ptr + rdb_amount_of_matched_text;

				rdb_current_state = rdb_get_previous_state();

				rdb_cp = rdb_c_buf_p;
				rdb_bp = rdbtext_ptr + YY_MORE_ADJ;
				goto rdb_match;

			case EOB_ACT_LAST_MATCH:
				rdb_c_buf_p =
				&rdb_current_buffer->rdb_ch_buf[rdb_n_chars];

				rdb_current_state = rdb_get_previous_state();

				rdb_cp = rdb_c_buf_p;
				rdb_bp = rdbtext_ptr + YY_MORE_ADJ;
				goto rdb_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of rdblex */


/* rdb_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int rdb_get_next_buffer()
	{
	register char *dest = rdb_current_buffer->rdb_ch_buf;
	register char *source = rdbtext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( rdb_c_buf_p > &rdb_current_buffer->rdb_ch_buf[rdb_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( rdb_current_buffer->rdb_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( rdb_c_buf_p - rdbtext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (rdb_c_buf_p - rdbtext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( rdb_current_buffer->rdb_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		rdb_current_buffer->rdb_n_chars = rdb_n_chars = 0;

	else
		{
		int num_to_read =
			rdb_current_buffer->rdb_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = rdb_current_buffer;

			int rdb_c_buf_p_offset =
				(int) (rdb_c_buf_p - b->rdb_ch_buf);

			if ( b->rdb_is_our_buffer )
				{
				int new_size = b->rdb_buf_size * 2;

				if ( new_size <= 0 )
					b->rdb_buf_size += b->rdb_buf_size / 8;
				else
					b->rdb_buf_size *= 2;

				b->rdb_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					rdb_flex_realloc( (void *) b->rdb_ch_buf,
							 b->rdb_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->rdb_ch_buf = 0;

			if ( ! b->rdb_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			rdb_c_buf_p = &b->rdb_ch_buf[rdb_c_buf_p_offset];

			num_to_read = rdb_current_buffer->rdb_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&rdb_current_buffer->rdb_ch_buf[number_to_move]),
			rdb_n_chars, num_to_read );

		rdb_current_buffer->rdb_n_chars = rdb_n_chars;
		}

	if ( rdb_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			rdbrestart( rdbin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			rdb_current_buffer->rdb_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	rdb_n_chars += number_to_move;
	rdb_current_buffer->rdb_ch_buf[rdb_n_chars] = YY_END_OF_BUFFER_CHAR;
	rdb_current_buffer->rdb_ch_buf[rdb_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	rdbtext_ptr = &rdb_current_buffer->rdb_ch_buf[0];

	return ret_val;
	}


/* rdb_get_previous_state - get the state just before the EOB char was reached */

static rdb_state_type rdb_get_previous_state()
	{
	register rdb_state_type rdb_current_state;
	register char *rdb_cp;

	rdb_current_state = rdb_start;

	for ( rdb_cp = rdbtext_ptr + YY_MORE_ADJ; rdb_cp < rdb_c_buf_p; ++rdb_cp )
		{
		register YY_CHAR rdb_c = (*rdb_cp ? rdb_ec[YY_SC_TO_UI(*rdb_cp)] : 1);
		if ( rdb_accept[rdb_current_state] )
			{
			rdb_last_accepting_state = rdb_current_state;
			rdb_last_accepting_cpos = rdb_cp;
			}
		while ( rdb_chk[rdb_base[rdb_current_state] + rdb_c] != rdb_current_state )
			{
			rdb_current_state = (int) rdb_def[rdb_current_state];
			if ( rdb_current_state >= 47 )
				rdb_c = rdb_meta[(unsigned int) rdb_c];
			}
		rdb_current_state = rdb_nxt[rdb_base[rdb_current_state] + (unsigned int) rdb_c];
		}

	return rdb_current_state;
	}


/* rdb_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = rdb_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static rdb_state_type rdb_try_NUL_trans( rdb_state_type rdb_current_state )
#else
static rdb_state_type rdb_try_NUL_trans( rdb_current_state )
rdb_state_type rdb_current_state;
#endif
	{
	register int rdb_is_jam;
	register char *rdb_cp = rdb_c_buf_p;

	register YY_CHAR rdb_c = 1;
	if ( rdb_accept[rdb_current_state] )
		{
		rdb_last_accepting_state = rdb_current_state;
		rdb_last_accepting_cpos = rdb_cp;
		}
	while ( rdb_chk[rdb_base[rdb_current_state] + rdb_c] != rdb_current_state )
		{
		rdb_current_state = (int) rdb_def[rdb_current_state];
		if ( rdb_current_state >= 47 )
			rdb_c = rdb_meta[(unsigned int) rdb_c];
		}
	rdb_current_state = rdb_nxt[rdb_base[rdb_current_state] + (unsigned int) rdb_c];
	rdb_is_jam = (rdb_current_state == 46);

	return rdb_is_jam ? 0 : rdb_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void rdbunput( int c, register char *rdb_bp )
#else
static void rdbunput( c, rdb_bp )
int c;
register char *rdb_bp;
#endif
	{
	register char *rdb_cp = rdb_c_buf_p;

	/* undo effects of setting up rdbtext */
	*rdb_cp = rdb_hold_char;

	if ( rdb_cp < rdb_current_buffer->rdb_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = rdb_n_chars + 2;
		register char *dest = &rdb_current_buffer->rdb_ch_buf[
					rdb_current_buffer->rdb_buf_size + 2];
		register char *source =
				&rdb_current_buffer->rdb_ch_buf[number_to_move];

		while ( source > rdb_current_buffer->rdb_ch_buf )
			*--dest = *--source;

		rdb_cp += (int) (dest - source);
		rdb_bp += (int) (dest - source);
		rdb_current_buffer->rdb_n_chars =
			rdb_n_chars = rdb_current_buffer->rdb_buf_size;

		if ( rdb_cp < rdb_current_buffer->rdb_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--rdb_cp = (char) c;


	rdbtext_ptr = rdb_bp;
	rdb_hold_char = *rdb_cp;
	rdb_c_buf_p = rdb_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int rdbinput()
#else
static int input()
#endif
	{
	int c;

	*rdb_c_buf_p = rdb_hold_char;

	if ( *rdb_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* rdb_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( rdb_c_buf_p < &rdb_current_buffer->rdb_ch_buf[rdb_n_chars] )
			/* This was really a NUL. */
			*rdb_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = rdb_c_buf_p - rdbtext_ptr;
			++rdb_c_buf_p;

			switch ( rdb_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because rdb_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					rdbrestart( rdbin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( rdbwrap() )
						return EOF;

					if ( ! rdb_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return rdbinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					rdb_c_buf_p = rdbtext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) rdb_c_buf_p;	/* cast for 8-bit char's */
	*rdb_c_buf_p = '\0';	/* preserve rdbtext */
	rdb_hold_char = *++rdb_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void rdbrestart( FILE *input_file )
#else
void rdbrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! rdb_current_buffer )
		rdb_current_buffer = rdb_create_buffer( rdbin, YY_BUF_SIZE );

	rdb_init_buffer( rdb_current_buffer, input_file );
	rdb_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void rdb_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void rdb_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( rdb_current_buffer == new_buffer )
		return;

	if ( rdb_current_buffer )
		{
		/* Flush out information for old buffer. */
		*rdb_c_buf_p = rdb_hold_char;
		rdb_current_buffer->rdb_buf_pos = rdb_c_buf_p;
		rdb_current_buffer->rdb_n_chars = rdb_n_chars;
		}

	rdb_current_buffer = new_buffer;
	rdb_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (rdbwrap()) processing, but the only time this flag
	 * is looked at is after rdbwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	rdb_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void rdb_load_buffer_state( void )
#else
void rdb_load_buffer_state()
#endif
	{
	rdb_n_chars = rdb_current_buffer->rdb_n_chars;
	rdbtext_ptr = rdb_c_buf_p = rdb_current_buffer->rdb_buf_pos;
	rdbin = rdb_current_buffer->rdb_input_file;
	rdb_hold_char = *rdb_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE rdb_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE rdb_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) rdb_flex_alloc( sizeof( struct rdb_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in rdb_create_buffer()" );

	b->rdb_buf_size = size;

	/* rdb_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->rdb_ch_buf = (char *) rdb_flex_alloc( b->rdb_buf_size + 2 );
	if ( ! b->rdb_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in rdb_create_buffer()" );

	b->rdb_is_our_buffer = 1;

	rdb_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void rdb_delete_buffer( YY_BUFFER_STATE b )
#else
void rdb_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == rdb_current_buffer )
		rdb_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->rdb_is_our_buffer )
		rdb_flex_free( (void *) b->rdb_ch_buf );

	rdb_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void rdb_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void rdb_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	rdb_flush_buffer( b );

	b->rdb_input_file = file;
	b->rdb_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->rdb_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->rdb_is_interactive = 0;
#else
	b->rdb_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void rdb_flush_buffer( YY_BUFFER_STATE b )
#else
void rdb_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->rdb_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->rdb_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->rdb_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->rdb_buf_pos = &b->rdb_ch_buf[0];

	b->rdb_at_bol = 1;
	b->rdb_buffer_status = YY_BUFFER_NEW;

	if ( b == rdb_current_buffer )
		rdb_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE rdb_scan_buffer( char *base, rdb_size_t size )
#else
YY_BUFFER_STATE rdb_scan_buffer( base, size )
char *base;
rdb_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) rdb_flex_alloc( sizeof( struct rdb_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in rdb_scan_buffer()" );

	b->rdb_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->rdb_buf_pos = b->rdb_ch_buf = base;
	b->rdb_is_our_buffer = 0;
	b->rdb_input_file = 0;
	b->rdb_n_chars = b->rdb_buf_size;
	b->rdb_is_interactive = 0;
	b->rdb_at_bol = 1;
	b->rdb_fill_buffer = 0;
	b->rdb_buffer_status = YY_BUFFER_NEW;

	rdb_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE rdb_scan_string( rdbconst char *rdb_str )
#else
YY_BUFFER_STATE rdb_scan_string( rdb_str )
rdbconst char *rdb_str;
#endif
	{
	int len;
	for ( len = 0; rdb_str[len]; ++len )
		;

	return rdb_scan_bytes( rdb_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE rdb_scan_bytes( rdbconst char *bytes, int len )
#else
YY_BUFFER_STATE rdb_scan_bytes( bytes, len )
rdbconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	rdb_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) rdb_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in rdb_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = rdb_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in rdb_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->rdb_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void rdb_push_state( int new_state )
#else
static void rdb_push_state( new_state )
int new_state;
#endif
	{
	if ( rdb_start_stack_ptr >= rdb_start_stack_depth )
		{
		rdb_size_t new_size;

		rdb_start_stack_depth += YY_START_STACK_INCR;
		new_size = rdb_start_stack_depth * sizeof( int );

		if ( ! rdb_start_stack )
			rdb_start_stack = (int *) rdb_flex_alloc( new_size );

		else
			rdb_start_stack = (int *) rdb_flex_realloc(
					(void *) rdb_start_stack, new_size );

		if ( ! rdb_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	rdb_start_stack[rdb_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void rdb_pop_state()
	{
	if ( --rdb_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(rdb_start_stack[rdb_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int rdb_top_state()
	{
	return rdb_start_stack[rdb_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void rdb_fatal_error( rdbconst char msg[] )
#else
static void rdb_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine rdbless() so it works in section 3 code. */

#undef rdbless
#define rdbless(n) \
	do \
		{ \
		/* Undo effects of setting up rdbtext. */ \
		rdbtext[rdbleng] = rdb_hold_char; \
		rdb_c_buf_p = rdbtext + n; \
		rdb_hold_char = *rdb_c_buf_p; \
		*rdb_c_buf_p = '\0'; \
		rdbleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef rdbtext_ptr
#ifdef YY_USE_PROTOS
static void rdb_flex_strncpy( char *s1, rdbconst char *s2, int n )
#else
static void rdb_flex_strncpy( s1, s2, n )
char *s1;
rdbconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int rdb_flex_strlen( rdbconst char *s )
#else
static int rdb_flex_strlen( s )
rdbconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *rdb_flex_alloc( rdb_size_t size )
#else
static void *rdb_flex_alloc( size )
rdb_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *rdb_flex_realloc( void *ptr, rdb_size_t size )
#else
static void *rdb_flex_realloc( ptr, size )
void *ptr;
rdb_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void rdb_flex_free( void *ptr )
#else
static void rdb_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	rdblex();
	return 0;
	}
#endif
#line 129 "rdb.l"



ParamList *RDBParFile(f)
			FILE	*f;
{
		static parser = 0;

	if ( parser ) {
		rdbrestart((FILE *) f);
		BEGIN(0);
	} else {
		rdbin = (void *) f;
		parser = 1;
	}

	result = NULL;
	if ( !rdblex() && result ){
            PFree(result);
	    result = (ParamList *)NULL;
         }

	return result;
}
