HEADERS = guidecamaz.h
OBJECTS = azcamio.o  azcam.o  frame.o  guidecamaz.o
LIBS    = -lfuntools -lmsg -lparam -lutil -lsla
TARGET  = guidecamaz
MAKE_TARGET = $(MAKE_SERVER_TARGET)
include ../../include/Makefile.inc
